clone_folder: c:\go\src\github.com\sosedoff\pgweb

environment:
  GOPATH: c:\gopath

services:
  - postgresql

install:
  - set PATH=%GOPATH%\bin;%PATH%
  - echo %PATH%
  - echo %GOPATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - go env
  - go version
  - dep ensure

build_script:
  - go build

test_script:
  - go test -race -cover ./...

deploy: off