name: Build artifacts

on: pull_request

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Make binaries
        uses: sosedoff/actions/golang-build@master
        with:
          args: linux/amd64 darwin/amd64

      - name: Upload to Amazon S3
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 cp --acl public-read /github/workspace/.release/*.zip s3://pgweb-github-builds/$GITHUB_REF/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        